// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBPCHJGka58Glk-8qYE7XNeAlMPalrmY',
    appId: '1:759277915002:web:b5794a3fd9de0ed4b5a4c3',
    messagingSenderId: '759277915002',
    projectId: 'snapshot-pinterest-clone',
    authDomain: 'snapshot-pinterest-clone.firebaseapp.com',
    storageBucket: 'snapshot-pinterest-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb81JztxEuFarHNdYlixnzD2grXZSw6aI',
    appId: '1:759277915002:android:9037358287954c0cb5a4c3',
    messagingSenderId: '759277915002',
    projectId: 'snapshot-pinterest-clone',
    storageBucket: 'snapshot-pinterest-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL9r2nZw_OpOJdoM3GT6L9dWNsBXvHlCQ',
    appId: '1:759277915002:ios:4c0dba8fae537c7cb5a4c3',
    messagingSenderId: '759277915002',
    projectId: 'snapshot-pinterest-clone',
    storageBucket: 'snapshot-pinterest-clone.appspot.com',
    iosClientId: '759277915002-ehgbgbg6e86ah74r9vbk7m7df9c48k3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapShot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL9r2nZw_OpOJdoM3GT6L9dWNsBXvHlCQ',
    appId: '1:759277915002:ios:4c0dba8fae537c7cb5a4c3',
    messagingSenderId: '759277915002',
    projectId: 'snapshot-pinterest-clone',
    storageBucket: 'snapshot-pinterest-clone.appspot.com',
    iosClientId: '759277915002-ehgbgbg6e86ah74r9vbk7m7df9c48k3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapShot',
  );
}
